data:
  dataset: DSprites
  filepath: /mnt/cephfs/home/voz/shared/database/disentanglement/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz
  n_samples: 10000

encoder1:
  arch: resnet20
  
encoder2:
  arch: mlp
  hidden_layer_sizes: [16, 16, 8, 8, 16, 16]

training:
  n_epochs: 50
  save_epochs: 50
  batch_size: &batch_size 128
  optimizer:
    optimizer: Adam
    base_lr: 0.001
    base_batch_size: 128
    batch_size: *batch_size
  scheduler:
    scheduler: StepLR
    step_size: 20
    gamma: 0.3