data:
  dataset: Shapes3D
  filepath: /mnt/cephfs/home/voz/shared/database/disentanglement/3dshapes.h5
  n_samples: 10000

encoder1:
  arch: resnet20
  
encoder2:
  arch: mlp
  hidden_layer_sizes: [64, 64, 32, 32, 64, 64]

training:
  temperature: 0.01
  n_epochs: 50
  save_epochs: 50
  batch_size: &batch_size 128
  optimizer:
    optimizer: Adam
    base_lr: 0.001
    base_batch_size: 128
    batch_size: *batch_size
  scheduler:
    scheduler: StepLR
    step_size: 20
    gamma: 0.3